Repository sonata-project/SonataPageBundle, pull requests merged in 2018-06, with the labels that each got.

#993 Remove default value for parent association mappings
  src/Admin/BlockAdmin.php
  src/Admin/SnapshotAdmin.php
Labels: patch

#995 Force use breadcrumb translation strings for page admins
  src/Admin/BlockAdmin.php
  src/Admin/PageAdmin.php
  src/Admin/SiteAdmin.php
  src/Admin/SnapshotAdmin.php
Labels: patch

#996 Auto-register datepicker form theme
  src/DependencyInjection/SonataPageExtension.php
  tests/DependencyInjection/SonataPageExtensionTest.php
Labels: minor

#999 Moved asset to root directory
  .gitattributes
  .gitignore
  assets/gulp/config.js
  assets/gulp/index.js
  assets/gulp/tasks/css.js
  assets/gulp/tasks/default.js
  assets/gulp/tasks/js.js
  assets/gulp/tasks/watch.js
  assets/gulp/util/banner.js
  assets/gulp/util/scriptFilter.js
  assets/src/js/composer.js
  assets/src/js/page.js
  assets/src/js/treeview.js
  assets/src/scss/composer.scss
  assets/src/scss/default.scss
  assets/src/scss/page.scss
  assets/src/scss/tree.scss
  docs/reference/assets.rst
  gulpfile.js
  package.json
  src/Resources/assets_src/.gitignore
Labels: pedantic
