Repository sonata-project/SonataPageBundle, pull requests merged in 2018-02, with the labels that each got.

#952 Changed default templates for system pages
  src/Resources/views/Exceptions/list.html.twig
  src/Resources/views/Page/create.html.twig
Labels: patch

#955 Support higher version of Slugify
  composer.json
Labels: patch

#957 Minor composer improvements
  composer.json
Labels: pedantic

#958 Commands as services
  src/DependencyInjection/SonataPageExtension.php
  src/Resources/config/command.xml
Labels: patch

#956 Update installation documentation for Symfony Flex
  .gitignore
  docs/reference/installation.rst
Labels: docs

#960 Auto-register sonata.page.router
  docs/reference/installation.rst
  src/DependencyInjection/Compiler/CmfRouterCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataPageExtension.php
  src/SonataPageBundle.php
  tests/DependencyInjection/Compiler/CmfRouterAutoRegisterTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataPageExtensionTest.php
Labels: minor

#963 Make services public
  src/DependencyInjection/SonataPageExtension.php
Labels: patch

#967 Revert "Update Page.php"
  src/Model/Page.php
Labels: pedantic
