Repository sonata-project/SonataPageBundle, pull requests merged in 2020-07, with the labels that each got.

#1173 Fix RestFul API
  src/Resources/config/api_controllers.xml
  src/Resources/config/routing/api.xml
Labels: patch

#1162 Make SonataEasyExtends optional
  UPGRADE-3.x.md
  composer.json
  docs/reference/advanced_configuration.rst
  docs/reference/installation.rst
  src/DependencyInjection/SonataPageExtension.php
  tests/App/AppKernel.php
  tests/DependencyInjection/Compiler/CmfRouterAutoRegisterTest.php
  tests/DependencyInjection/SonataPageExtensionTest.php
Labels: minor

#1176 Not all persistence bundles are implemented here
  docs/reference/installation.rst
Labels: pedantic
