Repository sonata-project/SonataPageBundle, pull requests merged in 2021-11, with the labels that each got.

#1377 Fix validation
  assets/src/js/composer.js
  src/Resources/public/sonata-page.back.js
  src/Resources/public/sonata-page.back.min.js
Labels: patch

#1382 Configure PHPStan and Psalm
  .github/workflows/qa.yaml
  composer.json
  phpstan.neon.dist
  psalm.xml
  src/Admin/BaseBlockAdmin.php
  src/Admin/BlockAdmin.php
  src/Admin/PageAdmin.php
  src/Admin/SharedBlockAdmin.php
  src/Admin/SiteAdmin.php
  src/Admin/SnapshotAdmin.php
  src/Block/BlockContextManager.php
  src/Block/ChildrenPagesBlockService.php
  src/Block/ContainerBlockService.php
  src/Block/PageListBlockService.php
  src/Block/SharedBlockBlockService.php
  src/CmsManager/BaseCmsPageManager.php
  src/CmsManager/CmsManagerInterface.php
  src/CmsManager/CmsManagerSelector.php
  src/CmsManager/CmsPageManager.php
  src/CmsManager/CmsSnapshotManager.php
  src/Command/UpdateCoreRoutesCommand.php
  src/Consumer/CreateSnapshotsConsumer.php
  src/Controller/AjaxController.php
  src/Controller/Api/BlockController.php
  src/Controller/Api/PageController.php
  src/Controller/Api/SiteController.php
  src/DependencyInjection/SonataPageExtension.php
  src/Entity/BaseBlock.php
  src/Entity/BlockManager.php
  src/Entity/PageManager.php
  src/Entity/SiteManager.php
  src/Entity/SnapshotManager.php
  src/Entity/Transformer.php
  src/Listener/ExceptionListener.php
  src/Model/Block.php
  src/Model/Page.php
  src/Model/Site.php
  src/Model/SiteInterface.php
  src/Model/Snapshot.php
  src/Model/SnapshotPageProxy.php
  src/Model/TransformerInterface.php
  src/Route/CmsPageRouter.php
  src/Twig/Extension/PageExtension.php
  src/Twig/GlobalVariables.php
  src/Validator/UniqueUrlValidator.php
  tests/App/AppKernel.php
  tests/Block/ContainerBlockServiceTest.php
  tests/CmsManager/CmsPageManagerTest.php
  tests/Form/Type/PageSelectorTypeTest.php
  tests/Form/Type/TemplateChoiceTypeTest.php
  tests/Listener/ExceptionListenerTest.php
  tests/Listener/RequestListenerTest.php
  tests/Listener/ResponseListenerTest.php
  tests/Page/PageServiceManagerTest.php
  tests/Page/Service/DefaultPageServiceTest.php
  tests/Site/BaseLocaleSiteSelectorTest.php
  tests/Site/HostPathSiteSelectorTest.php
  tests/Site/HostSiteSelectorTest.php
Labels: minor

#1386 Solve next major related to the API REST
  composer.json
  src/Block/SharedBlockBlockService.php
  src/Command/BaseCommand.php
  src/Controller/Api/BlockController.php
  src/Controller/Api/FOSRestController.php
  src/Controller/Api/PageController.php
  src/Controller/Api/SiteController.php
  src/Controller/Api/SnapshotController.php
  src/DependencyInjection/SonataPageExtension.php
  src/Entity/BlockInteractor.php
  src/Entity/BlockManager.php
  src/Entity/PageManager.php
  src/Entity/SiteManager.php
  src/Entity/SnapshotManager.php
  src/Entity/Transformer.php
  src/Form/Type/ApiBlockType.php
  src/Form/Type/ApiPageType.php
  src/Form/Type/ApiSiteType.php
  src/Model/PageManagerInterface.php
  src/Model/SiteManagerInterface.php
  src/Model/SnapshotManagerInterface.php
  src/Resources/config/api_controllers.xml
  src/Resources/config/api_form.xml
  src/Resources/config/serializer.xml
  src/Resources/config/serializer/Model.Block.xml
  src/Resources/config/serializer/Model.Page.xml
  src/Resources/config/serializer/Model.Site.xml
  src/Resources/config/serializer/Model.Snapshot.xml
  src/Serializer/BlockSerializerHandler.php
  src/Serializer/PageSerializerHandler.php
  src/Serializer/SiteSerializerHandler.php
  src/Serializer/SnapshotSerializerHandler.php
  src/SonataPageBundle.php
  tests/Controller/Api/AjaxControllerTest.php
  tests/Controller/Api/BlockControllerTest.php
  tests/Controller/Api/PageControllerTest.php
  tests/Controller/Api/SiteControllerTest.php
  tests/Controller/Api/SnapshotControllerTest.php
  tests/DependencyInjection/SonataPageExtensionTest.php
  tests/Entity/BlockManagerTest.php
  tests/Entity/PageManagerTest.php
  tests/Entity/SiteManagerTest.php
  tests/Entity/SnapshotManagerTest.php
Labels: major
