Repository sonata-project/SonataPageBundle, pull requests merged in 2022-07, with the labels that each got.

#1427 Make Cache dependency optional
  composer.json
  src/Admin/BaseBlockAdmin.php
  src/Admin/PageAdmin.php
  src/Admin/SnapshotAdmin.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataPageExtension.php
  src/Resources/config/admin.xml
  tests/App/config/sonata.yaml
  tests/DependencyInjection/ConfigurationTest.php
Labels: minor

#1418 Decouple and Deprecate notification bundle from create snapshot code
  composer.json
  src/Admin/Extension/CreateSnapshotAdminExtension.php
  src/Command/BaseCommand.php
  src/Command/CreateSnapshotsCommand.php
  src/Consumer/CreateSnapshotConsumer.php
  src/Consumer/CreateSnapshotsConsumer.php
  src/Controller/PageAdminController.php
  src/Controller/SiteAdminController.php
  src/Controller/SnapshotAdminController.php
  src/DependencyInjection/SonataPageExtension.php
  src/Resources/config/admin.xml
  src/Resources/config/command.xml
  src/Resources/config/service.xml
  src/Service/Contract/CreateSnapshotByPageInterface.php
  src/Service/Contract/CreateSnapshotBySiteInterface.php
  src/Service/CreateSnapshotService.php
  tests/Admin/Extension/CreateSnapshotAdminExtensionTest.php
  tests/Command/CreateSnapshotsCommandTest.php
  tests/Controller/PageAdminControllerTest.php
  tests/Functional/ResetableDBWebTestTest.php
  tests/Functional/Ticket/Issue1134Test.php
  tests/Service/CreateSnapshotServiceTest.php
  tests/custom_bootstrap.php
Labels: minor

#1435 More Deprecation for Cache removal
  src/Cache/BlockEsiCache.php
  src/Cache/BlockJsCache.php
  src/Cache/BlockSsiCache.php
  src/DependencyInjection/Configuration.php
Labels: minor

#1430 Remove Cache
  composer.json
  docs/index.rst
  docs/reference/advanced_configuration.rst
  docs/reference/advanced_usage.rst
  docs/reference/command_line.rst
  docs/reference/installation.rst
  docs/reference/introduction.rst
  docs/reference/varnish.rst
  src/Admin/BaseBlockAdmin.php
  src/Admin/PageAdmin.php
  src/Admin/SnapshotAdmin.php
  src/Cache/BlockEsiCache.php
  src/Cache/BlockJsCache.php
  src/Cache/BlockSsiCache.php
  src/DependencyInjection/Compiler/CacheCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataPageExtension.php
  src/Resources/config/admin.xml
  src/Resources/config/cache.xml
  src/Resources/config/routing/cache.xml
  src/Resources/translations/SonataPageBundle.bg.xliff
  src/Resources/translations/SonataPageBundle.de.xliff
  src/Resources/translations/SonataPageBundle.en.xliff
  src/Resources/translations/SonataPageBundle.es.xliff
  src/Resources/translations/SonataPageBundle.fr.xliff
  src/Resources/translations/SonataPageBundle.hu.xliff
  src/Resources/translations/SonataPageBundle.it.xliff
  src/Resources/translations/SonataPageBundle.ja.xliff
  src/Resources/translations/SonataPageBundle.nl.xliff
  src/Resources/translations/SonataPageBundle.pt_BR.xliff
  src/Resources/translations/SonataPageBundle.ru.xliff
  src/Resources/translations/SonataPageBundle.sk.xliff
  src/Resources/translations/SonataPageBundle.sl.xliff
  src/SonataPageBundle.php
  tests/App/AppKernel.php
  tests/App/config/sonata.yaml
  tests/Cache/BlockEsiCacheTest.php
  tests/Cache/BlockJsCacheTest.php
  tests/Cache/BlockSsiCacheTest.php
  tests/DependencyInjection/Compiler/CacheCompilerPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: major

#1436 PageExtension without deprecated InitRuntimeInterface
  src/Resources/config/twig.xml
  src/Twig/Extension/PageExtension.php
  tests/Twig/Extension/PageExtensionTest.php
Labels: major

#1440 Solve multiple deprecations
  src/Admin/PageAdmin.php
  src/Admin/SnapshotAdmin.php
  src/CmsManager/BaseCmsPageManager.php
  src/CmsManager/CmsPageManager.php
  src/CmsManager/CmsSnapshotManager.php
  src/Controller/SiteAdminController.php
  src/Listener/ResponseListener.php
  src/Route/RoutePageGenerator.php
  tests/Admin/BaseBlockAdminTest.php
  tests/Admin/PageAdminTest.php
  tests/Block/PageListBlockServiceTest.php
  tests/CmsManager/CmsPageManagerTest.php
  tests/CmsManager/CmsSnapshotManagerTest.php
  tests/DependencyInjection/Compiler/GlobalVariablesCompilerPassTest.php
Labels: pedantic

#1443 Remove BaseBlockAdmin getPersistentParameters
  src/Admin/BaseBlockAdmin.php
Labels: major

#1444 Change sonata.templating by twig where it's possible
  src/Block/ChildrenPagesBlockService.php
  src/Block/ContainerBlockService.php
  src/Block/PageListBlockService.php
  src/Block/SharedBlockBlockService.php
  src/Listener/ExceptionListener.php
  src/Listener/ResponseListener.php
  src/Model/SnapshotChildrenCollection.php
  src/Page/TemplateManager.php
  src/Page/TemplateManagerInterface.php
  src/Resources/config/block.xml
  src/Resources/config/http_kernel.xml
  src/Resources/config/page.xml
  tests/Block/ContainerBlockServiceTest.php
  tests/Block/PageListBlockServiceTest.php
  tests/Listener/ExceptionListenerTest.php
  tests/Listener/ResponseListenerTest.php
  tests/Page/TemplateManagerTest.php
  tests/Route/RoutePageGeneratorTest.php
Labels: major

#1449 Remove SonataCoreBundle
  composer.json
  docs/reference/advanced_configuration.rst
  docs/reference/installation.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataPageExtension.php
  src/Resources/views/base_error.html.twig
  src/SonataPageBundle.php
  tests/App/AppKernel.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataPageExtensionTest.php
  tests/SonataPageBundleTest.php
Labels: major

#1450 Add Twig 3 compatibility
  composer.json
  tests/Page/TemplateManagerTest.php
Labels: major

#1451 Add support for some Symfony 5.4/6.0 components
  composer.json
  tests/Page/TemplateManagerTest.php
Labels: major

#1456 Remove SonataNotificationBundle
  composer.json
  docs/reference/command_line.rst
  docs/reference/installation.rst
  src/Admin/Extension/CreateSnapshotAdminExtension.php
  src/Command/BaseCommand.php
  src/Command/CleanupSnapshotsCommand.php
  src/Command/CreateSnapshotsCommand.php
  src/Consumer/CleanupSnapshotConsumer.php
  src/Consumer/CleanupSnapshotsConsumer.php
  src/Consumer/CreateSnapshotConsumer.php
  src/Consumer/CreateSnapshotsConsumer.php
  src/Controller/PageAdminController.php
  src/Controller/SiteAdminController.php
  src/DependencyInjection/SonataPageExtension.php
  src/Resources/config/consumer.xml
  tests/Admin/Extension/CreateSnapshotAdminExtensionTest.php
  tests/App/AppKernel.php
  tests/App/config/sonata.yaml
  tests/Command/CleanupSnapshotsCommandTest.php
  tests/Command/CreateSnapshotsCommandTest.php
  tests/Controller/PageAdminControllerTest.php
Labels: major

#1457 Remove deprecated SonataEasyExtendsBundle code
  src/DependencyInjection/SonataPageExtension.php
Labels: major

#1464 Add PHP 8.1
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  src/Model/SnapshotPageProxy.php
Labels: major

#1468 Fix event class deprecations
  src/Listener/RequestListener.php
  src/Site/BaseSiteSelector.php
  src/Site/HostByLocaleSiteSelector.php
  src/Site/HostPathByLocaleSiteSelector.php
  src/Site/HostPathSiteSelector.php
  src/Site/HostSiteSelector.php
  src/Site/SiteSelectorInterface.php
  tests/Listener/RequestListenerTest.php
  tests/Site/HostByLocaleSiteSelectorTest.php
  tests/Site/HostPathByLocaleSiteSelectorTest.php
  tests/Site/HostPathSiteSelectorTest.php
  tests/Site/HostSiteSelectorTest.php
  tests/Site/SubRequestsSiteSelectorTest.php
Labels: major

#1446 SnapshotManager: use QueryBuilder
  composer.json
  src/Entity/SnapshotManager.php
  tests/App/Entity/SonataPageBlock.php
  tests/App/Entity/SonataPagePage.php
  tests/App/Entity/SonataPageSite.php
  tests/App/Entity/SonataPageSnapshot.php
  tests/Entity/BlockManagerTest.php
  tests/Entity/PageManagerTest.php
  tests/Entity/SiteManagerTest.php
  tests/Entity/SnapshotManagerTest.php
  tests/Functional/Snapshot/SnapshotManagerTest.php
Labels: minor

#1433 Solve most NEXT_MAJOR comments
  src/Admin/Extension/CreateSnapshotAdminExtension.php
  src/CmsManager/CmsSnapshotManager.php
  src/Command/CreateSiteCommand.php
  src/Controller/PageController.php
  src/Controller/SiteAdminController.php
  src/Controller/SnapshotAdminController.php
  src/DependencyInjection/SonataPageExtension.php
  src/Entity/SnapshotManager.php
  src/Form/Type/PageTypeChoiceType.php
  src/Form/Type/TemplateChoiceType.php
  src/Generator/Mustache.php
  src/Listener/ResponseListener.php
  src/Model/SnapshotChildrenCollection.php
  src/Model/SnapshotManagerInterface.php
  src/Resources/config/orm.xml
  src/Resources/config/page.xml
  src/Resources/views/PageAdmin/compose.html.twig
  src/Route/CmsPageRouter.php
  tests/Admin/BaseBlockAdminTest.php
  tests/CmsManager/CmsSnapshotManagerTest.php
  tests/Command/CleanupSnapshotsCommandTest.php
  tests/Command/CreateSiteCommandTest.php
  tests/Command/CreateSnapshotsCommandTest.php
  tests/Entity/SnapshotManagerTest.php
  tests/Model/PageTest.php
  tests/Route/CmsPageRouterTest.php
Labels: major

#1475 Remove another NEXT_MAJOR comment
  src/Form/Type/CreateSnapshotType.php
  src/Form/Type/PageSelectorType.php
Labels: major

#1482 Remove target page code
  src/Command/CloneSiteCommand.php
  src/Entity/Transformer.php
  src/Model/Page.php
  src/Model/PageInterface.php
  src/Model/Snapshot.php
  src/Model/SnapshotInterface.php
  src/Model/SnapshotPageProxy.php
  src/Page/PageServiceManager.php
  tests/Model/PageTest.php
Labels: minor

#1441 Add rector
  .gitattributes
  .github/workflows/qa.yaml
  Makefile
  composer.json
  rector.php
  src/Admin/BlockAdmin.php
  src/Admin/PageAdmin.php
  src/Block/BreadcrumbBlockService.php
  src/Block/ContainerBlockService.php
  src/Block/PageListBlockService.php
  src/Block/SharedBlockBlockService.php
  src/Cache/BlockJsCache.php
  src/Command/BaseCommand.php
  src/Command/CreateSnapshotsCommand.php
  src/Command/MigrateToJsonTypeCommand.php
  src/Command/RenderBlockCommand.php
  src/Form/Type/PageSelectorType.php
  src/Generator/Mustache.php
  src/Listener/ExceptionListener.php
  src/Listener/ResponseListener.php
  src/Mapper/PageFormMapper.php
  src/Model/Page.php
  src/Model/SnapshotPageProxy.php
  src/Model/SnapshotPageProxyFactory.php
  src/Request/RequestFactory.php
  src/Request/SiteRequestContext.php
  src/Route/CmsPageRouter.php
  src/Site/BaseSiteSelector.php
  src/Twig/Extension/PageExtension.php
  tests/App/Entity/SonataPageSnapshot.php
  tests/CmsManager/CmsPageManagerTest.php
  tests/CmsManager/CmsSnapshotManagerTest.php
  tests/Command/BaseCommandTest.php
  tests/Command/CloneSiteCommandTest.php
  tests/Command/CreateSiteCommandTest.php
  tests/Controller/PageAdminControllerTest.php
  tests/Entity/Snapshot.php
  tests/Entity/SnapshotManagerTest.php
  tests/Form/Type/TemplateChoiceTypeTest.php
  tests/Listener/ExceptionListenerTest.php
  tests/Listener/ResponseListenerTest.php
  tests/Page/PageServiceManagerTest.php
  tests/Page/Service/DefaultPageServiceTest.php
  tests/Resources/XliffTest.php
  tests/Route/CmsPageRouterTest.php
  tests/Route/RoutePageGeneratorTest.php
  tests/Site/HostPathSiteSelectorTest.php
  tests/Site/HostSiteSelectorTest.php
Labels: pedantic

#1490 Use stable version of rector
  composer.json
Labels: pedantic

#1488 Remove everything related to target
  src/Command/CloneSiteCommand.php
  src/DependencyInjection/SonataPageExtension.php
  src/Entity/Transformer.php
  src/Model/Page.php
  src/Model/PageInterface.php
  src/Model/Snapshot.php
  src/Model/SnapshotInterface.php
  src/Model/SnapshotPageProxy.php
  src/Page/PageServiceManager.php
  src/Resources/config/doctrine/BaseSnapshot.orm.xml
  src/Resources/config/page.xml
  tests/Command/CloneSiteCommandTest.php
  tests/Model/PageTest.php
  tests/Page/PageServiceManagerTest.php
Labels: major

#1485 Upgrade to Sonata 4
  composer.json
  src/Admin/BaseBlockAdmin.php
  src/Admin/BlockAdmin.php
  src/Admin/Extension/CreateSnapshotAdminExtension.php
  src/Admin/PageAdmin.php
  src/Admin/SharedBlockAdmin.php
  src/Admin/SiteAdmin.php
  src/Admin/SnapshotAdmin.php
  src/Controller/BlockAdminController.php
  src/Controller/PageAdminController.php
  src/Controller/SiteAdminController.php
  src/Controller/SnapshotAdminController.php
  src/DependencyInjection/SonataPageExtension.php
  src/Resources/config/admin.xml
  src/Resources/config/block.xml
  src/Resources/config/controllers.xml
  src/Resources/config/orm.xml
  src/Resources/config/page.xml
  src/Resources/config/service.xml
  tests/Admin/PageAdminTest.php
  tests/Controller/PageAdminControllerTest.php
Labels: major

#1471 Increase PHPStan to level 5 and Psalm to level 7
  phpstan.neon.dist
  psalm.xml
  src/Admin/BaseBlockAdmin.php
  src/CmsManager/CmsManagerInterface.php
  src/CmsManager/CmsPageManager.php
  src/CmsManager/CmsSnapshotManager.php
  src/Command/CleanupSnapshotsCommand.php
  src/Command/CreateSnapshotsCommand.php
  src/Command/UpdateCoreRoutesCommand.php
  src/Controller/PageController.php
  src/Entity/BlockManager.php
  src/Listener/ExceptionListener.php
  src/Mapper/PageFormMapper.php
  src/Model/Page.php
  src/Model/PageInterface.php
  src/Model/SnapshotPageProxy.php
  src/Route/RoutePageGenerator.php
Labels: major

#1491 Add Support for Symfony 5 and 6
  .github/workflows/test.yaml
  composer.json
  docs/reference/installation.rst
  src/CmsManager/BCLogoutHandlerInterface.php
  src/CmsManager/CmsManagerSelector.php
  src/CmsManager/DecoratorStrategy.php
  src/Command/CleanupSnapshotsCommand.php
  src/Command/CloneSiteCommand.php
  src/Command/CreateBlockContainerCommand.php
  src/Command/CreateSiteCommand.php
  src/Command/CreateSnapshotsCommand.php
  src/Command/UpdateCoreRoutesCommand.php
  src/Controller/AjaxController.php
  src/Controller/BlockController.php
  src/Controller/PageController.php
  src/DependencyInjection/Configuration.php
  src/Form/Type/CreateSnapshotType.php
  src/Form/Type/PageSelectorType.php
  src/Form/Type/PageTypeChoiceType.php
  src/Form/Type/TemplateChoiceType.php
  src/Listener/ResponseListener.php
  src/Request/SiteRequestContext.php
  src/Resources/config/admin.xml
  src/Resources/config/controllers.xml
  src/Resources/config/page.xml
  src/Resources/views/PageAdmin/compose.html.twig
  src/Route/CmsPageRouter.php
  src/Site/BaseSiteSelector.php
  src/Twig/Extension/PageExtension.php
  src/Validator/Constraints/UniqueUrl.php
  tests/App/AppKernel.php
  tests/App/config/config.yaml
  tests/App/config/config_sonata_block_v4.yaml
  tests/App/config/config_symfony_v4.yaml
  tests/App/config/config_symfony_v5.yaml
  tests/App/config/security.yaml
  tests/Command/CleanupSnapshotsCommandTest.php
  tests/Command/CreateBlockContainerCommandTest.php
  tests/Command/CreateSnapshotsCommandTest.php
  tests/Controller/PageAdminControllerTest.php
  tests/Functional/Ticket/Issue1134Test.php
  tests/Listener/ResponseListenerTest.php
  tests/Route/CmsPageRouterTest.php
  tests/Service/CleanupSnapshotServiceTest.php
  tests/Service/CreateSnapshotServiceTest.php
  tests/Validator/UniqueUrlValidatorTest.php
Labels: major

#1499 fix accessMapping
  src/Admin/BlockAdmin.php
  src/Admin/PageAdmin.php
  src/Admin/SnapshotAdmin.php
Labels: major

#1500 Avoid SonataBlockBundle deprecations
  composer.json
  src/CmsManager/CmsSnapshotManager.php
  src/Entity/BlockInteractor.php
  src/Entity/PageManager.php
  src/Entity/Transformer.php
  src/Model/Block.php
  src/Model/Page.php
  src/Model/PageInterface.php
  src/Model/SnapshotPageProxy.php
  tests/CmsManager/CmsSnapshotManagerTest.php
  tests/Entity/PageManagerTest.php
Labels: major

#1502 Fix unreachable create_snapshots field
  src/Admin/SiteAdmin.php
Labels: major

#1507 Fix share block block service
  src/Block/SharedBlockBlockService.php
Labels: major

#1508 Use DateTimeInterface instead of DateTime
  src/Command/CreateSiteCommand.php
  src/Entity/SnapshotManager.php
  src/Model/Page.php
  src/Model/PageInterface.php
  src/Model/Site.php
  src/Model/SiteInterface.php
  src/Model/Snapshot.php
  src/Model/SnapshotInterface.php
  src/Model/SnapshotManagerInterface.php
  src/Model/SnapshotPageProxy.php
  tests/Functional/Snapshot/SnapshotManagerTest.php
Labels: major

#1509 Remove more deprecated code
  src/Entity/SnapshotManager.php
  src/Model/Page.php
  src/Model/Snapshot.php
Labels: major

#1510 Move from protected to private when possible
  src/Admin/BlockAdmin.php
  src/Admin/Extension/CreateSnapshotAdminExtension.php
  src/Admin/PageAdmin.php
  src/Admin/SiteAdmin.php
  src/Block/SharedBlockBlockService.php
  src/CmsManager/CmsPageManager.php
  src/CmsManager/CmsSnapshotManager.php
  src/Entity/PageManager.php
  src/Entity/SnapshotManager.php
  src/Form/Type/PageSelectorType.php
  src/Form/Type/PageTypeChoiceType.php
  src/Form/Type/TemplateChoiceType.php
  src/Page/Service/DefaultPageService.php
  src/Request/SiteRequestContext.php
  src/Validator/UniqueUrlValidator.php
  tests/Block/PageListBlockServiceTest.php
  tests/CmsManager/CmsPageManagerTest.php
  tests/CmsManager/CmsSnapshotManagerTest.php
  tests/Entity/BlockInteractorTest.php
  tests/Form/Type/PageSelectorTypeTest.php
  tests/Form/Type/TemplateChoiceTypeTest.php
  tests/Functional/Snapshot/SnapshotManagerTest.php
  tests/Listener/ExceptionListenerTest.php
  tests/Listener/ResponseListenerTest.php
  tests/Page/PageServiceManagerTest.php
  tests/Page/Service/DefaultPageServiceTest.php
  tests/Resources/XliffTest.php
  tests/Route/CmsPageRouterTest.php
  tests/Route/RoutePageGeneratorTest.php
  tests/Site/HostPathSiteSelectorTest.php
  tests/Twig/Extension/PageExtensionTest.php
  tests/Validator/UniqueUrlValidatorTest.php
Labels: major

#1511 Deprecate slugify_service
  src/DependencyInjection/Configuration.php
Labels: minor

#1506 Remove Slugify Method
  docs/reference/advanced_configuration.rst
  docs/reference/installation.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataPageExtension.php
  src/Entity/PageManager.php
  src/Model/Page.php
  src/Resources/config/orm.xml
  src/SonataPageBundle.php
  tests/App/config/sonata.yaml
  tests/DependencyInjection/ConfigurationTest.php
  tests/Entity/PageManagerTest.php
  tests/Model/PageTest.php
  tests/SonataPageBundleTest.php
Labels: major

#1512 Add type to model and entity folder
  src/Command/CreateBlockContainerCommand.php
  src/Entity/BaseBlock.php
  src/Entity/BasePage.php
  src/Entity/BaseSite.php
  src/Entity/BaseSnapshot.php
  src/Entity/BlockInteractor.php
  src/Entity/BlockManager.php
  src/Entity/SiteManager.php
  src/Entity/SnapshotManager.php
  src/Model/Block.php
  src/Model/BlockInteractorInterface.php
  src/Model/BlockManagerInterface.php
  src/Model/Page.php
  src/Model/PageBlockInterface.php
  src/Model/PageInterface.php
  src/Model/PageManagerInterface.php
  src/Model/Site.php
  src/Model/SiteInterface.php
  src/Model/SiteManagerInterface.php
  src/Model/Snapshot.php
  src/Model/SnapshotChildrenCollection.php
  src/Model/SnapshotInterface.php
  src/Model/SnapshotManagerInterface.php
  src/Model/SnapshotPageProxy.php
  src/Model/SnapshotPageProxyFactory.php
  src/Model/SnapshotPageProxyFactoryInterface.php
  src/Model/SnapshotPageProxyInterface.php
  tests/App/Entity/SonataPageBlock.php
  tests/App/Entity/SonataPagePage.php
  tests/App/Entity/SonataPageSite.php
  tests/App/Entity/SonataPageSnapshot.php
  tests/CmsManager/CmsPageManagerTest.php
  tests/CmsManager/CmsSnapshotManagerTest.php
  tests/Entity/BlockInteractorTest.php
  tests/Entity/Snapshot.php
  tests/Functional/Ticket/Issue1134Test.php
  tests/Model/BlockInteractorTest.php
  tests/Model/Page.php
  tests/Model/PageTest.php
  tests/Model/Site.php
Labels: major
