Repository sonata-project/SonataPageBundle, pull requests merged in 2022-08, with the labels that each got.

#1513 Increase PHPStan to level 7
  phpstan.neon.dist
  src/Admin/PageAdmin.php
  src/Block/ChildrenPagesBlockService.php
  src/Block/SharedBlockBlockService.php
  src/CmsManager/BaseCmsPageManager.php
  src/CmsManager/CmsManagerInterface.php
  src/CmsManager/CmsManagerSelector.php
  src/CmsManager/CmsManagerSelectorInterface.php
  src/CmsManager/CmsPageManager.php
  src/CmsManager/CmsSnapshotManager.php
  src/CmsManager/DecoratorStrategy.php
  src/Command/CleanupSnapshotsCommand.php
  src/Controller/SnapshotAdminController.php
  src/DependencyInjection/SonataPageExtension.php
  src/Entity/BlockInteractor.php
  src/Entity/Transformer.php
  src/Model/BlockInteractorInterface.php
  src/Model/SnapshotPageProxy.php
  src/Model/TransformerInterface.php
  src/Request/RequestFactory.php
  src/Resources/config/page.xml
  src/Resources/config/twig.xml
  src/Site/BaseSiteSelector.php
  src/Template/Matrix/Parser.php
  src/Twig/GlobalVariables.php
  tests/DependencyInjection/SonataPageExtensionTest.php
  tests/Entity/BlockInteractorTest.php
  tests/Functional/Snapshot/SnapshotManagerTest.php
  tests/Resources/XliffTest.php
  tests/Route/RoutePageGeneratorTest.php
Labels: major

#1517 Delete .styleci.yml
  .styleci.yml
Labels: pedantic

#1520 Add support for Twig and Doctrine extensions 2.0
  composer.json
  src/Command/CloneSiteCommand.php
  src/Entity/PageManager.php
  tests/Command/CreateBlockContainerCommandTest.php
  tests/Route/RoutePageGeneratorTest.php
Labels: major

#1516 Transformer test
  src/Entity/Transformer.php
  tests/Entity/TransformerTest.php
Labels: pedantic

#1523 Fix phpstan
  tests/Entity/TransformerTest.php
Labels: pedantic

#1518 Increase Psalm to level 4
  psalm.xml
  src/CmsManager/BaseCmsPageManager.php
  src/CmsManager/CmsManagerInterface.php
  src/CmsManager/CmsPageManager.php
  src/Entity/BlockInteractor.php
  src/Entity/Transformer.php
  src/Model/BlockInteractorInterface.php
  src/Model/Page.php
  src/Model/PageInterface.php
  src/Model/SiteInterface.php
  src/Model/SnapshotPageProxy.php
  src/Model/TransformerInterface.php
  src/Request/SiteRequestContext.php
  src/Resources/config/page.xml
  src/Route/CmsPageRouter.php
  src/Site/BaseSiteSelector.php
  src/Template/Matrix/Parser.php
  src/Twig/GlobalVariables.php
  tests/Command/CleanupSnapshotsCommandTest.php
  tests/Command/CreateSnapshotsCommandTest.php
  tests/Entity/TransformerTest.php
  tests/Functional/Ticket/Issue1134Test.php
  tests/Route/CmsPageRouterTest.php
Labels: major

#1519 Increase PHPStan to level 8
  phpstan.neon.dist
  src/Admin/BlockAdmin.php
  src/Admin/Extension/CreateSnapshotAdminExtension.php
  src/Admin/PageAdmin.php
  src/Block/BreadcrumbBlockService.php
  src/Block/ChildrenPagesBlockService.php
  src/Block/PageListBlockService.php
  src/Block/SharedBlockBlockService.php
  src/Command/CleanupSnapshotsCommand.php
  src/Command/CloneSiteCommand.php
  src/Command/CreateBlockContainerCommand.php
  src/Command/CreateSiteCommand.php
  src/Command/CreateSnapshotsCommand.php
  src/Command/UpdateCoreRoutesCommand.php
  src/Entity/BlockInteractor.php
  src/Entity/BlockManager.php
  src/Entity/PageManager.php
  src/Entity/SnapshotManager.php
  src/Entity/Transformer.php
  src/Listener/ExceptionListener.php
  src/Model/Page.php
  src/Model/PageInterface.php
  src/Model/Snapshot.php
  src/Model/SnapshotInterface.php
  src/Model/SnapshotPageProxy.php
  src/Page/Service/DefaultPageService.php
  src/Request/SiteRequestContext.php
  src/Request/SiteRequestContextInterface.php
  src/Resources/config/admin.xml
  src/Route/CmsPageRouter.php
  src/Route/RoutePageGenerator.php
  src/Site/HostPathByLocaleSiteSelector.php
  src/Site/HostPathSiteSelector.php
  src/Twig/Extension/PageExtension.php
  src/Twig/GlobalVariables.php
  tests/Admin/PageAdminTest.php
  tests/CmsManager/CmsPageManagerTest.php
  tests/CmsManager/CmsSnapshotManagerTest.php
  tests/Functional/Snapshot/SnapshotManagerTest.php
  tests/Functional/Ticket/Issue1134Test.php
  tests/Listener/ExceptionListenerTest.php
  tests/Model/PageTest.php
  tests/Site/HostByLocaleSiteSelectorTest.php
  tests/Site/HostPathSiteSelectorTest.php
  tests/Site/HostSiteSelectorTest.php
  tests/Site/SubRequestsSiteSelectorTest.php
Labels: major

#1525 Add PHPStan Strict plugin
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  src/Admin/BlockAdmin.php
  src/Admin/PageAdmin.php
  src/Admin/SharedBlockAdmin.php
  src/Admin/SiteAdmin.php
  src/Block/BreadcrumbBlockService.php
  src/Block/ChildrenPagesBlockService.php
  src/CmsManager/CmsManagerSelector.php
  src/CmsManager/CmsPageManager.php
  src/CmsManager/CmsSnapshotManager.php
  src/CmsManager/DecoratorStrategy.php
  src/Command/CloneSiteCommand.php
  src/Command/CreateSiteCommand.php
  src/Controller/BlockAdminController.php
  src/Controller/PageAdminController.php
  src/Controller/SiteAdminController.php
  src/Controller/SnapshotAdminController.php
  src/DependencyInjection/Compiler/CmfRouterCompilerPass.php
  src/Entity/BlockInteractor.php
  src/Entity/PageManager.php
  src/Entity/SnapshotManager.php
  src/Entity/Transformer.php
  src/Form/Type/PageSelectorType.php
  src/Listener/ExceptionListener.php
  src/Listener/RequestListener.php
  src/Listener/ResponseListener.php
  src/Model/Page.php
  src/Model/SnapshotPageProxy.php
  src/Page/PageServiceManager.php
  src/Page/Service/DefaultPageService.php
  src/Page/TemplateManager.php
  src/Page/TemplateManagerInterface.php
  src/Request/SiteRequestContext.php
  src/Route/CmsPageRouter.php
  src/Route/RoutePageGenerator.php
  src/Site/BaseSiteSelector.php
  src/Site/HostByLocaleSiteSelector.php
  src/Site/HostPathByLocaleSiteSelector.php
  src/Site/HostPathSiteSelector.php
  src/Site/HostSiteSelector.php
  src/Twig/Extension/PageExtension.php
  src/Validator/UniqueUrlValidator.php
  tests/App/Entity/SonataPageBlock.php
  tests/App/Entity/SonataPagePage.php
  tests/App/Entity/SonataPageSite.php
  tests/App/Entity/SonataPageSnapshot.php
  tests/Entity/PageManagerTest.php
  tests/Entity/TransformerTest.php
  tests/Form/Type/PageSelectorTypeTest.php
  tests/Listener/RequestListenerTest.php
  tests/Model/PageTest.php
  tests/Page/TemplateManagerTest.php
  tests/Route/CmsPageRouterTest.php
  tests/Site/BaseLocaleSiteSelectorTest.php
  tests/Site/HostPathSiteSelectorTest.php
  tests/Site/HostSiteSelectorTest.php
Labels: major

#1526 Increase Psalm to level 3
  psalm.xml
  src/Admin/BaseBlockAdmin.php
  src/Admin/PageAdmin.php
  src/Block/ChildrenPagesBlockService.php
  src/CmsManager/CmsPageManager.php
  src/CmsManager/CmsSnapshotManager.php
  src/Command/CleanupSnapshotsCommand.php
  src/Command/CloneSiteCommand.php
  src/Command/CreateBlockContainerCommand.php
  src/Command/CreateSiteCommand.php
  src/Command/CreateSnapshotsCommand.php
  src/DependencyInjection/Configuration.php
  src/Entity/BlockInteractor.php
  src/Entity/PageManager.php
  src/Entity/Transformer.php
  src/Form/Type/PageSelectorType.php
  src/Listener/ExceptionListener.php
  src/Listener/RequestListener.php
  src/Model/Page.php
  src/Model/Site.php
  src/Model/Template.php
  src/Model/TransformerInterface.php
  src/Page/PageServiceManager.php
  src/Page/PageServiceManagerInterface.php
  src/Page/Service/DefaultPageService.php
  src/Route/CmsPageRouter.php
  src/Route/RoutePageGenerator.php
  src/Site/BaseSiteSelector.php
  src/Site/HostPathByLocaleSiteSelector.php
  src/Site/HostPathSiteSelector.php
  src/Template/Matrix/Parser.php
  src/Twig/Extension/PageExtension.php
  tests/Functional/Snapshot/SnapshotManagerTest.php
  tests/Listener/ExceptionListenerTest.php
  tests/Model/TemplateTest.php
  tests/Twig/Extension/PageExtensionTest.php
Labels: major

#1527 Fix tests
  tests/CmsManager/CmsPageManagerTest.php
  tests/CmsManager/CmsSnapshotManagerTest.php
Labels: pedantic

#1529 Cleanup removed code
  docs/index.rst
  docs/reference/api.rst
  src/Resources/config/doctrine/Block.orm.xml.skeleton
  src/Resources/config/doctrine/Page.orm.xml.skeleton
  src/Resources/config/doctrine/Site.orm.xml.skeleton
  src/Resources/config/doctrine/Snapshot.orm.xml.skeleton
  src/Resources/config/routing/api.xml
  src/Resources/config/routing/api/block.xml
  src/Resources/config/routing/api/page.xml
  src/Resources/config/routing/api/site.xml
  src/Resources/config/routing/api/snapshot.xml
Labels: major

#1528 Increase Psalm to level 2
  psalm.xml
  src/Admin/BaseBlockAdmin.php
  src/Admin/BlockAdmin.php
  src/Admin/PageAdmin.php
  src/CmsManager/BaseCmsPageManager.php
  src/CmsManager/CmsManagerInterface.php
  src/CmsManager/DecoratorStrategy.php
  src/DependencyInjection/Configuration.php
  src/Entity/SnapshotManager.php
  src/Form/Type/PageSelectorType.php
  src/Model/SnapshotChildrenCollection.php
  src/Request/RequestFactory.php
  src/Resources/config/admin.xml
  tests/App/AppKernel.php
  tests/CmsManager/CmsPageManagerTest.php
  tests/CmsManager/DecoratorStrategyTest.php
  tests/Entity/SnapshotManagerTest.php
  tests/Listener/ExceptionListenerTest.php
  tests/Listener/RequestListenerTest.php
  tests/Listener/ResponseListenerTest.php
  tests/Route/RoutePageGeneratorTest.php
  tests/Site/HostByLocaleSiteSelectorTest.php
  tests/Site/HostPathByLocaleSiteSelectorTest.php
  tests/Site/HostPathSiteSelectorTest.php
  tests/Site/HostSiteSelectorTest.php
  tests/Site/SubRequestsSiteSelectorTest.php
Labels: major

#1532 Add test for weird cases
  src/Entity/Transformer.php
  src/Model/TransformerInterface.php
  tests/Entity/TransformerTest.php
Labels: major

#1533 Remove usage of 'admin_pool' in twig templates
  composer.json
  phpunit.xml.dist
  src/Controller/PageAdminController.php
  src/Resources/views/BlockAdmin/compose_preview.html.twig
  src/Resources/views/PageAdmin/compose.html.twig
  tests/App/AppKernel.php
  tests/Functional/Admin/PageAdminTest.php
Labels: major

#1534 Add tests for Site and Snapshot Admins
  composer.json
  src/Admin/PageAdmin.php
  tests/Functional/Admin/SiteAdminTest.php
  tests/Functional/Admin/SnapshotAdminTest.php
Labels: major

#1524 Remove Block context manager
  UPGRADE-4.0.md
  docs/reference/installation.rst
  src/Block/BlockContextManager.php
  src/Resources/config/block.php
  src/Twig/Extension/PageExtension.php
  tests/App/config/sonata.yaml
  tests/Block/BlockContextManagerTest.php
Labels: major

#1536 fix Cleanup Query if no snapshot to keep
  src/Entity/SnapshotManager.php
  tests/Functional/Snapshot/SnapshotManagerTest.php
Labels: patch

#1542 Add test for Cleanup Snapshots Command
  tests/Command/CleanupSnapshotsCommandTest.php
  tests/Functional/Command/CleanupSnapshotsCommandTest.php
Labels: major

#1541 Remove unused controllers
  UPGRADE-4.0.md
  src/Controller/AjaxController.php
  src/Controller/BlockController.php
  src/Resources/config/block.php
  src/Resources/config/controllers.php
  src/Resources/config/routing/page.xml
Labels: major

#1539 Update snapshot resname & source
  src/Resources/translations/SonataPageBundle.bg.xliff
  src/Resources/translations/SonataPageBundle.de.xliff
  src/Resources/translations/SonataPageBundle.en.xliff
  src/Resources/translations/SonataPageBundle.es.xliff
  src/Resources/translations/SonataPageBundle.fr.xliff
  src/Resources/translations/SonataPageBundle.hu.xliff
  src/Resources/translations/SonataPageBundle.it.xliff
  src/Resources/translations/SonataPageBundle.ja.xliff
  src/Resources/translations/SonataPageBundle.nl.xliff
  src/Resources/translations/SonataPageBundle.pt_BR.xliff
  src/Resources/translations/SonataPageBundle.ru.xliff
  src/Resources/translations/SonataPageBundle.sk.xliff
  src/Resources/translations/SonataPageBundle.sl.xliff
Labels: major

#1548 Fix create snapshots
  src/Service/CreateSnapshotService.php
Labels: major

#1551 Add form tests for SnapshotAdmin
  src/Admin/SnapshotAdmin.php
  src/Controller/SnapshotAdminController.php
  src/Entity/Transformer.php
  src/Form/Type/CreateSnapshotType.php
  src/Model/TransformerInterface.php
  src/Resources/config/admin.php
  src/Resources/config/form.php
  src/Resources/views/SnapshotAdmin/create.html.twig
  tests/Controller/PageAdminControllerTest.php
  tests/Functional/Admin/SnapshotAdminTest.php
Labels: major

#1552 Add more CRUD form tests
  composer.json
  src/Admin/BlockAdmin.php
  src/Admin/SharedBlockAdmin.php
  src/Block/ChildrenPagesBlockService.php
  src/Block/SharedBlockBlockService.php
  src/Mapper/PageFormMapper.php
  src/Resources/config/block.php
  tests/Functional/Admin/SharedBlockAdminTest.php
  tests/Functional/Admin/SiteAdminTest.php
Labels: major

#1553 Add more tests
  composer.json
  tests/Block/ContainerBlockServiceTest.php
  tests/Functional/Admin/BlockAdminTest.php
  tests/Functional/Admin/PageAdminTest.php
  tests/Functional/Admin/SharedBlockAdminTest.php
Labels: major

#1546 Update trans unit
  src/Resources/translations/SonataPageBundle.bg.xliff
  src/Resources/translations/SonataPageBundle.de.xliff
  src/Resources/translations/SonataPageBundle.en.xliff
  src/Resources/translations/SonataPageBundle.es.xliff
  src/Resources/translations/SonataPageBundle.fr.xliff
  src/Resources/translations/SonataPageBundle.hu.xliff
  src/Resources/translations/SonataPageBundle.it.xliff
  src/Resources/translations/SonataPageBundle.ja.xliff
  src/Resources/translations/SonataPageBundle.nl.xliff
  src/Resources/translations/SonataPageBundle.pt_BR.xliff
  src/Resources/translations/SonataPageBundle.ru.xliff
  src/Resources/translations/SonataPageBundle.sk.xliff
  src/Resources/translations/SonataPageBundle.sl.xliff
  src/Resources/translations/validators.de.xliff
  src/Resources/translations/validators.en.xliff
  src/Resources/translations/validators.es.xliff
  src/Resources/translations/validators.fr.xliff
  src/Resources/translations/validators.hu.xliff
  src/Resources/translations/validators.it.xliff
  src/Resources/translations/validators.ja.xliff
  src/Resources/translations/validators.nl.xliff
  src/Resources/translations/validators.pt_BR.xliff
  src/Resources/translations/validators.ru.xliff
  src/Resources/translations/validators.sk.xliff
  src/Resources/translations/validators.sl.xliff
Labels: pedantic

#1555 Add more tests
  src/Admin/BlockAdmin.php
  src/Admin/PageAdmin.php
  src/Controller/BlockAdminController.php
  src/Resources/views/PageAdmin/compose.html.twig
  tests/Functional/Admin/BlockAdminTest.php
  tests/Functional/Admin/PageAdminTest.php
Labels: major

#1556 Add test for update disposition
  src/Admin/BaseBlockAdmin.php
  src/Controller/BlockAdminController.php
  src/Entity/BaseBlock.php
  src/Entity/BlockInteractor.php
  src/Entity/BlockManager.php
  src/Model/BlockInteractorInterface.php
  src/Model/BlockManagerInterface.php
  src/Resources/config/admin.php
  tests/Functional/Admin/BlockAdminTest.php
Labels: major

#1557 Add tests for render page via Snapshot
  src/Resources/views/PageAdmin/tree.html.twig
  src/Route/CmsPageRouter.php
  tests/Functional/Admin/SharedBlockAdminTest.php
  tests/Functional/Frontend/ExceptionsTest.php
  tests/Functional/Frontend/SnapshotTest.php
  tests/Route/CmsPageRouterTest.php
Labels: major

#1558 Add test for Page render being an editor
  tests/Functional/Admin/PageAdminTest.php
  tests/Functional/Admin/SharedBlockAdminTest.php
  tests/Functional/Frontend/PageTest.php
Labels: major

#1560 Fix tests
  tests/Admin/PageAdminTest.php
Labels: pedantic

#1559 Modernise frontend code
  .babelrc.js
  .eslintrc.js
  .github/workflows/frontend.yaml
  .prettierignore
  .stylelintrc.js
  UPGRADE-4.0.md
  assets/gulp/config.js
  assets/gulp/index.js
  assets/gulp/tasks/css.js
  assets/gulp/tasks/default.js
  assets/gulp/tasks/js.js
  assets/gulp/tasks/watch.js
  assets/gulp/util/banner.js
  assets/gulp/util/scriptFilter.js
  assets/js/app.js
  assets/js/composer.js
  assets/js/treeview.js
  assets/scss/app.scss
  assets/scss/composer.scss
  assets/scss/default.scss
  assets/scss/tree.scss
  assets/src/js/composer.js
  assets/src/js/treeview.js
  assets/src/scss/default.scss
  assets/src/scss/tree.scss
  docs/reference/advanced_configuration.rst
  docs/reference/installation.rst
  gulpfile.js
  package-lock.json
  package.json
  postcss.config.js
  prettier.config.js
  src/DependencyInjection/Configuration.php
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/public/entrypoints.json
  src/Resources/public/manifest.json
  src/Resources/public/sonata-page.back.css
  src/Resources/public/sonata-page.back.js
  src/Resources/public/sonata-page.back.min.css
  src/Resources/public/sonata-page.back.min.js
  src/Resources/public/sonata-page.front.css
  src/Resources/public/sonata-page.front.min.css
  src/Resources/views/base_error.html.twig
  tests/DependencyInjection/ConfigurationTest.php
  webpack.config.js
Labels: major

#1563 Fix block container children
  src/Admin/BaseBlockAdmin.php
  src/Admin/BlockAdmin.php
  tests/Functional/Admin/BlockAdminTest.php
  tests/Functional/Admin/SharedBlockAdminTest.php
Labels: major

#1515 Create test for templateManager
  composer.json
  src/Resources/views/layout.html.twig
  tests/Page/TemplateManagerTest.php
Labels: pedantic

#1566 Make composer page usable again
  assets/js/composer.js
  src/Admin/BlockAdmin.php
  src/Controller/PageAdminController.php
  src/Resources/public/app.js
  src/Resources/views/BlockAdmin/compose_preview.html.twig
  src/Template/Matrix/Parser.php
  tests/Functional/Admin/BlockAdminTest.php
Labels: major

#1567 Increase coverage
  tests/Functional/Admin/BlockAdminTest.php
  tests/Functional/Admin/PageAdminTest.php
Labels: major

#1568 Add test for render SonataPage blocks
  tests/Functional/Frontend/PageTest.php
  tests/Functional/Frontend/SnapshotTest.php
Labels: major

#1572 Fix breadcrumb context
  src/Block/BreadcrumbBlockService.php
  src/Resources/views/layout.html.twig
Labels: major

#1574 Remove show route for blocks
  src/Admin/BaseBlockAdmin.php
  src/Admin/SharedBlockAdmin.php
Labels: major

#1579 Do not extend SonataBlockBundle ContainerBlockService
  src/Block/ContainerBlockService.php
  src/Controller/PageAdminController.php
  src/Resources/config/block.php
  src/Resources/translations/SonataPageBundle.de.xliff
  src/Resources/translations/SonataPageBundle.en.xliff
  src/Resources/translations/SonataPageBundle.fr.xliff
  src/Resources/translations/SonataPageBundle.hu.xliff
  src/Resources/translations/SonataPageBundle.it.xliff
  src/Resources/translations/SonataPageBundle.nl.xliff
  tests/App/config/sonata.yaml
  tests/Block/ContainerBlockServiceTest.php
  tests/Functional/Admin/SharedBlockAdminTest.php
Labels: major

#1581 Adding notes in Upgrade file
  UPGRADE-4.0.md
Labels: pedantic
