Repository sonata-project/SonataPageBundle, pull requests merged in 2022-09, with the labels that each got.

#1582 Add panther test case
  .gitignore
  composer.json
  phpunit.xml.dist
  tests/App/public/index.php
  tests/Functional/Admin/BrowserTest.php
  tests/Functional/BasePantherTestCase.php
  tests/custom_bootstrap.php
Labels: major

#1591 Add tests for snapshots types
  tests/App/config/services.php
  tests/Functional/Admin/BlockAdminTest.php
  tests/Functional/Admin/PageAdminTest.php
  tests/Functional/Command/CloneSiteCommandTest.php
  tests/Functional/Frontend/PageTest.php
  tests/Functional/Frontend/SnapshotTest.php
Labels: major

#1587 Adding sonata block context into the doc
  docs/reference/installation.rst
Labels: docs

#1592 Fix breadcrumb block service
  composer.json
  src/Block/BreadcrumbBlockService.php
  src/Resources/config/block.php
  tests/Functional/Admin/SharedBlockAdminTest.php
Labels: major

#1595 Deprecated assets option
  UPGRADE-3.x.md
  src/DependencyInjection/Configuration.php
Labels: minor

#1598 Fix snapshots created through Snapshot Admin
  src/Admin/SnapshotAdmin.php
  src/Entity/SnapshotManager.php
  src/Resources/config/admin.php
  tests/Functional/Admin/SnapshotAdminTest.php
Labels: major

#1594 Removed deprecated blocks from base_layout.html.twig
  UPGRADE-4.0.md
  src/Resources/views/base_layout.html.twig
Labels: major

#1603 Use the new TransactionalManagerInterface
  composer.json
  src/Service/CleanupSnapshotService.php
  src/Service/CreateSnapshotService.php
  tests/Functional/Frontend/ExceptionsTest.php
  tests/Functional/Frontend/PageTest.php
  tests/Functional/Frontend/SnapshotTest.php
  tests/Service/CleanupSnapshotServiceTest.php
  tests/Service/CreateSnapshotServiceTest.php
  tests/Template/Matrix/ParserTest.php
Labels: pedantic

#1599 Fix block creation
  src/Block/ChildrenPagesBlockService.php
  src/Block/SharedBlockBlockService.php
  tests/Functional/Admin/PageAdminTest.php
  tests/Functional/Admin/SharedBlockAdminTest.php
Labels: major

#1605 Ensure each admin can access edit page
  src/Admin/PageAdmin.php
  src/Admin/SiteAdmin.php
  src/Admin/SnapshotAdmin.php
  src/Resources/views/SiteAdmin/list_action_create_snapshots.html.twig
  src/Resources/views/SiteAdmin/list_create_snapshots.html.twig
Labels: major

#1597 Accept enabled as string '1' and '0'
  src/Entity/Transformer.php
  src/Model/TransformerInterface.php
  tests/Entity/TransformerTest.php
Labels: major

#1608 Remove group legacy from tests
  tests/Form/Type/PageSelectorTypeTest.php
  tests/Route/CmsPageRouterTest.php
  tests/Validator/UniqueUrlValidatorTest.php
Labels: major

#1606 Fix request matcher to ensure we don't try to match / twice
  src/Admin/PageAdmin.php
  src/Site/BaseSiteSelector.php
  tests/Functional/Admin/PageAdminTest.php
  tests/Site/HostPathSiteSelectorTest.php
Labels: major

#1607 Fix custom url
  src/Entity/PageManager.php
  src/Entity/Transformer.php
  src/Route/CmsPageRouter.php
  tests/Functional/Admin/PageAdminTest.php
  tests/Functional/Frontend/PageTest.php
  tests/Functional/Frontend/SnapshotTest.php
  tests/Route/CmsPageRouterTest.php
Labels: major

#1618 Fix shared block service
  src/Block/SharedBlockBlockService.php
  src/Resources/config/block.php
Labels: major

#1615 Composer page not showing errors
  assets/js/composer.js
  composer.json
  package-lock.json
  src/Resources/public/app.js
  tests/Functional/Admin/BrowserTest.php
Labels: major

#1612 Poc to reuse MenuBlock
  composer.json
  src/Block/BreadcrumbBlockService.php
  src/Block/ChildrenPagesBlockService.php
  src/Block/ContainerBlockService.php
  src/Block/PageListBlockService.php
  src/Block/SharedBlockBlockService.php
  src/Resources/config/block.php
  src/Resources/translations/SonataPageBundle.bg.xliff
  src/Resources/translations/SonataPageBundle.de.xliff
  src/Resources/translations/SonataPageBundle.en.xliff
  src/Resources/translations/SonataPageBundle.es.xliff
  src/Resources/translations/SonataPageBundle.fr.xliff
  src/Resources/translations/SonataPageBundle.hu.xliff
  src/Resources/translations/SonataPageBundle.it.xliff
  src/Resources/translations/SonataPageBundle.ja.xliff
  src/Resources/translations/SonataPageBundle.nl.xliff
  src/Resources/translations/SonataPageBundle.pt_BR.xliff
  src/Resources/translations/SonataPageBundle.ru.xliff
  src/Resources/translations/SonataPageBundle.sk.xliff
  src/Resources/translations/SonataPageBundle.sl.xliff
  tests/Functional/Admin/SharedBlockAdminTest.php
Labels: major
