Repository sonata-project/SonataPageBundle, pull requests merged in 2023-05, with the labels that each got.

#1686 DevKit updates for 4.x branch
  .eslintrc.js
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  composer.json
  tests/Entity/SnapshotManagerTest.php
  tests/Functional/Frontend/ExceptionsTest.php
Labels: automerge, dev-kit

#1687 DevKit updates for 4.x branch
  .github/workflows/documentation.yaml
  .readthedocs.yaml
  docs/conf.py
  docs/reference/advanced_configuration.rst
  docs/reference/advanced_usage.rst
  docs/reference/error_pages.rst
  docs/reference/getting_started.rst
  docs/reference/multisite.rst
  docs/reference/twig_helpers.rst
  docs/requirements.txt
Labels: automerge, dev-kit

#1689 Up rector to 0.16
  composer.json
Labels: pedantic

#1690 DevKit updates for 4.x branch
  .github/workflows/test.yaml
  src/Admin/SiteAdmin.php
  src/Admin/SnapshotAdmin.php
Labels: automerge, dev-kit

#1692 Add support for form-extensions 2.0
  composer.json
Labels: minor

#1693 Release 4.3.0
  CHANGELOG.md
Labels: dev-kit
