Repository sonata-project/SonataPageBundle, pull requests merged in 2023-06, with the labels that each got.

#1695 Drop psalm 4, upgrade rector to 0.17
  composer.json
  src/CmsManager/CmsSnapshotManager.php
  src/Model/Template.php
Labels: pedantic

#1696 Add support for SonataBlockBundle 5.0
  .github/workflows/test.yaml
  composer.json
Labels: minor

#1697 Release 4.4.0
  CHANGELOG.md
Labels: dev-kit

#1698 Cleanup older upgrade files
  UPGRADE-3.x.md
  UPGRADE-4.x.md
Labels: pedantic
