Repository sonata-project/SonataPageBundle, pull requests merged in 2023-11, with the labels that each got.

#1721 Prevent to go to createByPage methode on Page deletion
  src/Admin/Extension/CreateSnapshotAdminExtension.php
  tests/Admin/Extension/CreateSnapshotAdminExtensionTest.php
Labels: minor

#1722 DevKit updates
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#1723 DevKit updates
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#1724 Solve deprecations
  composer.json
  src/Controller/BlockAdminController.php
  src/Controller/PageAdminController.php
  src/Controller/SiteAdminController.php
Labels: patch

#1729 Fix static analysis
  src/Entity/Transformer.php
  src/Model/TransformerInterface.php
  tests/Entity/TransformerTest.php
  tests/Functional/Entity/TransformerTest.php
Labels: pedantic

#1727 Add a runtime for the symfony/runtime component.
  composer.json
  docs/reference/multisite.rst
  src/Request/RequestFactory.php
  src/Runtime/SonataPagePathRuntime.php
  tests/Request/RequestFactoryTest.php
  tests/Runtime/SonataPagePathRuntimeTest.php
Labels: minor
