Repository sonata-project/SonataPageBundle, pull requests merged in 2023-12, with the labels that each got.

#1732 DevKit updates for 4.x branch
  rector.php
Labels: automerge, dev-kit

#1733 DevKit updates for 5.x branch
  rector.php
Labels: automerge, dev-kit

#1734 Fix CmsManagerSelector.isEditor always returns false
  src/CmsManager/CmsManagerSelector.php
  src/Resources/config/page.php
Labels: minor

#1739 Add symfony request factory in sonata runtime
  src/Runtime/SonataPagePathRuntime.php
Labels: patch

#1742 Fix phpstan
  src/CmsManager/CmsPageManager.php
  tests/CmsManager/CmsPageManagerTest.php
Labels: pedantic
