Repository sonata-project/SonataPageBundle, pull requests merged in 2023-03, with the labels that each got.

#1661 Fix page admin filter by type throwing
  src/Admin/PageAdmin.php
Labels: patch

#1665 Bump DAMA Doctrine Test Bundle
  composer.json
Labels: pedantic

#1668 Drop DAMA 6
  composer.json
Labels: pedantic

#1669 Use attributes on docs
  docs/reference/installation.rst
  tests/App/Entity/SonataPageBlock.php
Labels: docs

#1672 Use https for doctrine xml xsd
  src/Resources/config/doctrine/BaseBlock.orm.xml
  src/Resources/config/doctrine/BasePage.orm.xml
  src/Resources/config/doctrine/BaseSite.orm.xml
  src/Resources/config/doctrine/BaseSnapshot.orm.xml
Labels: pedantic
