Repository sonata-project/SonataPageBundle, pull requests merged in 2023-04, with the labels that each got.

#1676 Fix ORM mapping
  src/Resources/config/doctrine/BaseBlock.orm.xml
  src/Resources/config/doctrine/BasePage.orm.xml
  src/Resources/config/doctrine/BaseSite.orm.xml
  src/Resources/config/doctrine/BaseSnapshot.orm.xml
Labels: patch

#1679 Drop Symfony 4.4 and Twig 2
  .github/workflows/test.yaml
  composer.json
  src/CmsManager/BCLogoutHandlerInterface.php
  src/CmsManager/CmsManagerSelector.php
  src/CmsManager/DecoratorStrategy.php
  src/Command/CleanupSnapshotsCommand.php
  src/Command/CloneSiteCommand.php
  src/Command/CreateBlockContainerCommand.php
  src/Command/CreateSiteCommand.php
  src/Command/CreateSnapshotsCommand.php
  src/Command/UpdateCoreRoutesCommand.php
  src/Controller/BlockAdminController.php
  src/Resources/config/admin.php
  src/Resources/config/block.php
  src/Resources/config/command.php
  src/Resources/config/controllers.php
  src/Resources/config/form.php
  src/Resources/config/http_kernel.php
  src/Resources/config/orm.php
  src/Resources/config/page.php
  src/Resources/config/service.php
  src/Resources/config/slugify.php
  src/Resources/config/twig.php
  src/Resources/config/validators.php
  src/Site/BaseSiteSelector.php
  tests/App/AppKernel.php
  tests/App/config/config.yaml
  tests/App/config/config_symfony_v4.yaml
  tests/App/config/config_symfony_v5.yaml
  tests/App/config/config_symfony_v6.yaml
  tests/App/config/services.php
  tests/CmsManager/DecoratorStrategyTest.php
  tests/Functional/Admin/BlockAdminTest.php
  tests/Functional/Admin/BrowserTest.php
  tests/Functional/Admin/PageAdminTest.php
  tests/Functional/Admin/SharedBlockAdminTest.php
  tests/Functional/Admin/SiteAdminTest.php
  tests/Functional/Admin/SnapshotAdminTest.php
  tests/Functional/BasePantherTestCase.php
  tests/Functional/Command/CleanupSnapshotsCommandTest.php
  tests/Functional/Command/CloneSiteCommandTest.php
  tests/Functional/Command/CreateBlockContainerCommandTest.php
  tests/Functional/Command/CreateSiteCommandTest.php
  tests/Functional/Command/CreateSnapshotsCommandTest.php
  tests/Functional/Command/UpdateCoreRoutesCommandTest.php
  tests/Functional/Frontend/ExceptionsTest.php
  tests/Functional/Frontend/PageTest.php
  tests/Functional/Frontend/SnapshotTest.php
  tests/Functional/Ticket/Issue1134Test.php
  tests/Listener/ExceptionListenerTest.php
  tests/Listener/RequestListenerTest.php
  tests/Listener/ResponseListenerTest.php
  tests/Page/TemplateManagerTest.php
  tests/Site/HostByLocaleSiteSelectorTest.php
  tests/Site/HostPathByLocaleSiteSelectorTest.php
  tests/Site/HostPathSiteSelectorTest.php
  tests/Site/HostSiteSelectorTest.php
  tests/Site/SubRequestsSiteSelectorTest.php
Labels: minor

#1683 DevKit updates for 4.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#1684 DevKit updates for 5.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#1685 DevKit updates for 4.x branch
  README.md
Labels: automerge
