Repository sonata-project/SonataPageBundle, pull requests merged in 2024-06, with the labels that each got.

#1765 Bump rector
  composer.json
  psalm.xml
Labels: pedantic

#1766 DevKit updates for 4.x branch
  .github/workflows/documentation.yaml
  .github/workflows/frontend.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  tests/Entity/SnapshotManagerTest.php
Labels: automerge, dev-kit

#1767 Solve internal class usage
  src/DependencyInjection/SonataPageExtension.php
Labels: patch
