Repository sonata-project/SonataPageBundle, pull requests merged in 2024-12, with the labels that each got.

#1785 DevKit updates for 4.x branch
  .github/workflows/test.yaml
  rector.php
  tests/Functional/Frontend/ExceptionsTest.php
  tests/Functional/Frontend/PageTest.php
Labels: pedantic, automerge, dev-kit

#1788 DevKit updates for 4.x branch
  rector.php
Labels: automerge, dev-kit

#1787 Drop old versions of PHP and Symfony
  composer.json
  src/Listener/ExceptionListener.php
Labels: pedantic

#1790 DevKit updates for 4.x branch
  .eslintrc.js
Labels: automerge, dev-kit

#1791 DevKit updates for 5.x branch
  .eslintrc.js
Labels: automerge, dev-kit
